/* LinguaVerse · 多语种学习平台 · 数据模型
包含：语言元数据、分级课程、单词、语法、口语、听力、成就系统、社区帖子种子数据 */

const LANG_META = {
  en: { id: 'en', name: '英语', nativeName: 'English', flag: '🇬🇧', color: '#3b82f6', description: '全球通用语言，覆盖日常、商务、学术场景', levels: ['A1 入门','A2 基础','B1 中级','B2 高级'], difficulty: '★☆☆' },
  ja: { id: 'ja', name: '日语', nativeName: '日本語', flag: '🇯🇵', color: '#ef4444', description: '从五十音到JLPT N5-N1，系统学习日语', levels: ['N5 入门','N4 基础','N3 中级','N2 进阶'], difficulty: '★★☆' },
  ko: { id: 'ko', name: '韩语', nativeName: '한국어', flag: '🇰🇷', color: '#f59e0b', description: '从한글到TOPIK分级，轻松学韩语', levels: ['TOPIK 1','TOPIK 2','TOPIK 3','TOPIK 4'], difficulty: '★★☆' }
};

/* 分级课程 —— 每语言多级别，每级别多单元 */
const CURRICULUM = {
  en: [
    { level: 'A1 入门', desc: '掌握基本问候与日常交流，建议 8 小时', units: [
        { title: 'Greetings 问候', topic: 'hello', words: 8, duration: 25 },
        { title: 'Numbers 数字', topic: 'numbers', words: 10, duration: 25 },
        { title: 'Family 家庭', topic: 'family', words: 9, duration: 30 }] },
    { level: 'A2 基础', desc: '扩展词汇与简单语法，建议 12 小时', units: [
        { title: 'Daily routine 日常', topic: 'daily', words: 12, duration: 30 },
        { title: 'Food 餐饮', topic: 'food', words: 10, duration: 30 },
        { title: 'Travel 旅行', topic: 'travel', words: 11, duration: 30 }] },
    { level: 'B1 中级', desc: '能进行话题讨论，建议 16 小时', units: [
        { title: 'Work 工作', topic: 'work', words: 14, duration: 40 },
        { title: 'Opinions 观点', topic: 'opinions', words: 12, duration: 40 }] },
    { level: 'B2 高级', desc: '阅读长文本并表达复杂观点，建议 20 小时', units: [
        { title: 'Technology 科技', topic: 'tech', words: 16, duration: 50 },
        { title: 'Culture 文化', topic: 'culture', words: 15, duration: 50 }] }
  ],
  ja: [
    { level: 'N5 入门', desc: '五十音图与最基础词汇，建议 8 小时', units: [
        { title: '五十音（あ行）', topic: 'kana-a', words: 5, duration: 25 },
        { title: '五十音（か·さ·た行）', topic: 'kana-k', words: 15, duration: 30 },
        { title: '日常问候', topic: 'ja-greet', words: 8, duration: 25 }] },
    { level: 'N4 基础', desc: '基础动词、形容词与简单句', units: [
        { title: '动词基本形', topic: 'ja-verb', words: 12, duration: 30 },
        { title: '形容词活用', topic: 'ja-adj', words: 10, duration: 30 }] },
    { level: 'N3 中级', desc: '中长句与常用汉字 300', units: [
        { title: '～ている·可能形', topic: 'ja-adv', words: 14, duration: 40 },
        { title: '日常短文阅读', topic: 'ja-short', words: 12, duration: 40 }] },
    { level: 'N2 进阶', desc: '复杂语法与高级词汇', units: [
        { title: '敬语基础', topic: 'ja-honor', words: 15, duration: 50 },
        { title: '新闻听力', topic: 'ja-news', words: 14, duration: 50 }] }
  ],
  ko: [
    { level: 'TOPIK 1', desc: '한글 읽기与基础对话', units: [
        { title: '한글（元音与辅音）', topic: 'ko-hangul', words: 14, duration: 25 },
        { title: '问候与自我介绍', topic: 'ko-intro', words: 10, duration: 25 },
        { title: '数字与时间', topic: 'ko-num', words: 9, duration: 25 }] },
    { level: 'TOPIK 2', desc: '扩展常用动词与形容词', units: [
        { title: '饮食与购物', topic: 'ko-food', words: 12, duration: 30 },
        { title: '日常动词活用', topic: 'ko-verb', words: 11, duration: 30 }] },
    { level: 'TOPIK 3', desc: '复合句与中级阅读', units: [
        { title: '过去式与将来时', topic: 'ko-tense', words: 14, duration: 40 },
        { title: '日常短文阅读', topic: 'ko-reading', words: 12, duration: 40 }] },
    { level: 'TOPIK 4', desc: '高级语法与书面表达', units: [
        { title: '使动与被动', topic: 'ko-caus', words: 15, duration: 50 },
        { title: '议论文写作', topic: 'ko-essay', words: 14, duration: 50 }] }
  ]
};

/* 单词库（按主题） */
const WORDS = {
  hello:[
    {word:'Hello',meaning:'你好',example:'Hello, how are you?'},
    {word:'Good morning',meaning:'早上好',example:'Good morning, everyone.'},
    {word:'Goodbye',meaning:'再见',example:'Goodbye, see you tomorrow.'},
    {word:'Thank you',meaning:'谢谢',example:'Thank you very much.'},
    {word:'Sorry',meaning:'抱歉',example:"I'm sorry, I'm late."},
    {word:'Please',meaning:'请',example:'Please sit down.'},
    {word:'Excuse me',meaning:'打扰一下',example:'Excuse me, where is the restroom?'},
    {word:'Nice to meet you',meaning:'很高兴认识你',example:'Nice to meet you, John.'}],
  numbers:[
    {word:'One',meaning:'一',example:'I have one apple.'},
    {word:'Two',meaning:'二',example:'Two birds are singing.'},
    {word:'Three',meaning:'三',example:'Three cats.'},
    {word:'Four',meaning:'四',example:'Four seasons.'},
    {word:'Five',meaning:'五',example:'Five fingers.'},
    {word:'Ten',meaning:'十',example:'Ten minutes.'},
    {word:'Twenty',meaning:'二十',example:'Twenty dollars.'},
    {word:'Hundred',meaning:'一百',example:'A hundred people.'},
    {word:'Thousand',meaning:'一千',example:'A thousand miles.'},
    {word:'Million',meaning:'一百万',example:'A million stars.'}],
  family:[
    {word:'Father',meaning:'父亲',example:'My father is a teacher.'},
    {word:'Mother',meaning:'母亲',example:'My mother cooks well.'},
    {word:'Brother',meaning:'兄弟',example:'I have one brother.'},
    {word:'Sister',meaning:'姐妹',example:'My sister is younger.'},
    {word:'Grandfather',meaning:'祖父',example:'My grandfather is 80.'},
    {word:'Grandmother',meaning:'祖母',example:'Her grandmother lives in Paris.'},
    {word:'Uncle',meaning:'叔叔',example:'My uncle lives in New York.'},
    {word:'Aunt',meaning:'阿姨',example:'My aunt is a doctor.'},
    {word:'Cousin',meaning:'表/堂兄弟姐妹',example:'My cousin is my age.'}],
  daily:[
    {word:'Breakfast',meaning:'早餐',example:'I have breakfast at 7.'},
    {word:'Lunch',meaning:'午餐',example:'Lunch is ready.'},
    {word:'Dinner',meaning:'晚餐',example:'We had dinner together.'},
    {word:'Wake up',meaning:'醒来',example:'I wake up at 6:30.'},
    {word:'Work',meaning:'工作',example:'I work from 9 to 5.'},
    {word:'Study',meaning:'学习',example:'She studies English.'},
    {word:'Sleep',meaning:'睡觉',example:'I sleep at 11pm.'},
    {word:'Exercise',meaning:'锻炼',example:'I exercise every morning.'},
    {word:'Shower',meaning:'淋浴',example:'I take a shower.'},
    {word:'Commute',meaning:'通勤',example:'I commute by train.'},
    {word:'Meet',meaning:'见面',example:'Let us meet tomorrow.'},
    {word:'Relax',meaning:'放松',example:'I relax on weekends.'}],
  food:[
    {word:'Rice',meaning:'米饭',example:'I eat rice every day.'},
    {word:'Bread',meaning:'面包',example:'Bread with butter.'},
    {word:'Coffee',meaning:'咖啡',example:'A cup of coffee, please.'},
    {word:'Tea',meaning:'茶',example:'Green tea is healthy.'},
    {word:'Water',meaning:'水',example:'Drink more water.'},
    {word:'Meat',meaning:'肉',example:'I do not eat meat.'},
    {word:'Fish',meaning:'鱼',example:'This fish is fresh.'},
    {word:'Vegetable',meaning:'蔬菜',example:'Vegetables are good for you.'},
    {word:'Fruit',meaning:'水果',example:'Apple is my favorite fruit.'},
    {word:'Dessert',meaning:'甜点',example:'Chocolate cake for dessert.'}],
  travel:[
    {word:'Airport',meaning:'机场',example:'Meet me at the airport.'},
    {word:'Hotel',meaning:'酒店',example:'Book a hotel room.'},
    {word:'Ticket',meaning:'票',example:'I need a one-way ticket.'},
    {word:'Passport',meaning:'护照',example:'Show your passport.'},
    {word:'Luggage',meaning:'行李',example:'My luggage is heavy.'},
    {word:'Map',meaning:'地图',example:'Can I have a map?'},
    {word:'Station',meaning:'车站',example:'The train station is nearby.'},
    {word:'Tourist',meaning:'游客',example:'Many tourists visit here.'},
    {word:'Vacation',meaning:'假期',example:'I love summer vacation.'},
    {word:'Destination',meaning:'目的地',example:'Our destination is Paris.'},
    {word:'Reservation',meaning:'预订',example:'I made a reservation.'}],
  work:[
    {word:'Meeting',meaning:'会议',example:'The meeting starts at 10.'},
    {word:'Deadline',meaning:'截止日期',example:'The deadline is Friday.'},
    {word:'Colleague',meaning:'同事',example:'My colleague is helpful.'},
    {word:'Manager',meaning:'经理',example:'Our manager is fair.'},
    {word:'Contract',meaning:'合同',example:'Sign the contract.'},
    {word:'Salary',meaning:'薪水',example:'My salary is paid monthly.'},
    {word:'Project',meaning:'项目',example:'This project is important.'},
    {word:'Report',meaning:'报告',example:'Submit your report.'},
    {word:'Schedule',meaning:'日程',example:'Check the schedule.'},
    {word:'Interview',meaning:'面试',example:'I have an interview.'},
    {word:'Promotion',meaning:'晋升',example:'She got a promotion.'},
    {word:'Resume',meaning:'简历',example:'Update your resume.'},
    {word:'Experience',meaning:'经验',example:'Five years of experience.'},
    {word:'Responsibility',meaning:'责任',example:'Take responsibility.'}],
  opinions:[
    {word:'Agree',meaning:'同意',example:'I agree with you.'},
    {word:'Disagree',meaning:'不同意',example:"I'm afraid I disagree."},
    {word:'Opinion',meaning:'意见',example:"What's your opinion?"},
    {word:'Therefore',meaning:'因此',example:'Therefore, we should act.'},
    {word:'However',meaning:'然而',example:'However, there are risks.'},
    {word:'Perhaps',meaning:'也许',example:'Perhaps you are right.'},
    {word:'Definitely',meaning:'肯定地',example:'I definitely agree.'},
    {word:'Personally',meaning:'就个人而言',example:'Personally, I prefer tea.'},
    {word:'Suggest',meaning:'建议',example:'I suggest we wait.'},
    {word:'Recommend',meaning:'推荐',example:'I recommend this book.'},
    {word:'Persuade',meaning:'说服',example:'He persuaded me.'},
    {word:'Convince',meaning:'使相信',example:'She convinced me.'}],
  tech:[
    {word:'Artificial intelligence',meaning:'人工智能',example:'AI is transforming industries.'},
    {word:'Algorithm',meaning:'算法',example:'This algorithm is efficient.'},
    {word:'Blockchain',meaning:'区块链',example:'Blockchain is secure.'},
    {word:'Cloud computing',meaning:'云计算',example:'We use cloud computing.'},
    {word:'Cybersecurity',meaning:'网络安全',example:'Cybersecurity matters.'},
    {word:'Database',meaning:'数据库',example:'Store in a database.'},
    {word:'Encryption',meaning:'加密',example:'Use end-to-end encryption.'},
    {word:'Framework',meaning:'框架',example:'A modern framework.'},
    {word:'Interface',meaning:'接口/界面',example:'A clean user interface.'},
    {word:'Machine learning',meaning:'机器学习',example:'Machine learning models.'},
    {word:'Network',meaning:'网络',example:'A fast network.'},
    {word:'Platform',meaning:'平台',example:'A cross-platform app.'},
    {word:'Software',meaning:'软件',example:'Install new software.'},
    {word:'Virtual reality',meaning:'虚拟现实',example:'VR is immersive.'},
    {word:'Startup',meaning:'初创公司',example:'A successful startup.'},
    {word:'Innovation',meaning:'创新',example:'Drive innovation forward.'}],
  culture:[
    {word:'Heritage',meaning:'文化遗产',example:'Cultural heritage is precious.'},
    {word:'Tradition',meaning:'传统',example:'A long tradition.'},
    {word:'Literature',meaning:'文学',example:'World literature.'},
    {word:'Philosophy',meaning:'哲学',example:'Eastern philosophy.'},
    {word:'Architecture',meaning:'建筑',example:'Ancient architecture.'},
    {word:'Festival',meaning:'节日',example:'A traditional festival.'},
    {word:'Custom',meaning:'习俗',example:'Local customs.'},
    {word:'Identity',meaning:'身份',example:'Cultural identity.'},
    {word:'Diversity',meaning:'多样性',example:'Celebrate diversity.'},
    {word:'Perspective',meaning:'视角',example:'A new perspective.'},
    {word:'Ritual',meaning:'仪式',example:'A sacred ritual.'},
    {word:'Symbol',meaning:'符号',example:'A cultural symbol.'},
    {word:'Value',meaning:'价值观',example:'Core values.'},
    {word:'Celebration',meaning:'庆典',example:'A national celebration.'},
    {word:'Heritage',meaning:'遗产',example:'Protect our heritage.'}],
  'kana-a':[
    {word:'あ',meaning:'a',example:'あめ（雨）'},
    {word:'い',meaning:'i',example:'いぬ（犬）'},
    {word:'う',meaning:'u',example:'うみ（海）'},
    {word:'え',meaning:'e',example:'えき（駅）'},
    {word:'お',meaning:'o',example:'おとこ（男）'}],
  'kana-k':[
    {word:'か き く け こ',meaning:'ka ki ku ke ko',example:'かお（顔）'},
    {word:'さ し す せ そ',meaning:'sa shi su se so',example:'さけ（酒）'},
    {word:'た ち つ て と',meaning:'ta chi tsu te to',example:'たべる（食べる）'},
    {word:'な に ぬ ね の',meaning:'na ni nu ne no',example:'なまえ（名前）'},
    {word:'は ひ ふ へ ほ',meaning:'ha hi fu he ho',example:'はな（花）'},
    {word:'ま み む め も',meaning:'ma mi mu me mo',example:'まち（町）'},
    {word:'や ゆ よ',meaning:'ya yu yo',example:'やま（山）'},
    {word:'ら り る れ ろ',meaning:'ra ri ru re ro',example:'りんご'},
    {word:'わ を ん',meaning:'wa wo n',example:'わたし（私）'},
    {word:'が ぎ ぐ げ ご',meaning:'ga gi gu ge go',example:'がっこう（学校）'},
    {word:'ざ じ ず ぜ ぞ',meaning:'za ji zu ze zo',example:'ざっし（雑誌）'},
    {word:'だ ぢ づ で ど',meaning:'da ji zu de do',example:'でんしゃ（電車）'},
    {word:'ば び ぶ べ ぼ',meaning:'ba bi bu be bo',example:'ばんごう（番号）'},
    {word:'ぱ ぴ ぷ ぺ ぽ',meaning:'pa pi pu pe po',example:'ぱん（パン）'},
    {word:'きゃ きゅ きょ',meaning:'kya kyu kyo',example:'きょう（今日）'}],
  'ja-greet':[
    {word:'こんにちは',meaning:'你好',example:'こんにちは、田中さん。'},
    {word:'おはようございます',meaning:'早上好',example:'おはようございます、先生。'},
    {word:'こんばんは',meaning:'晚上好',example:'こんばんは、皆さん。'},
    {word:'ありがとう',meaning:'谢谢',example:'ありがとうございます。'},
    {word:'すみません',meaning:'不好意思/抱歉',example:'すみません、遅れました。'},
    {word:'さようなら',meaning:'再见',example:'さようなら、また明日。'},
    {word:'はじめまして',meaning:'初次见面',example:'はじめまして、鈴木です。'},
    {word:'お元気ですか',meaning:'你好吗',example:'お元気ですか？'}],
  'ja-verb':[
    {word:'食べる（たべる）',meaning:'吃',example:'朝ごはんを食べる。'},
    {word:'飲む（のむ）',meaning:'喝',example:'コーヒーを飲む。'},
    {word:'行く（いく）',meaning:'去',example:'学校に行く。'},
    {word:'来る（くる）',meaning:'来',example:'友達が来る。'},
    {word:'帰る（かえる）',meaning:'回',example:'家に帰る。'},
    {word:'見る（みる）',meaning:'看',example:'テレビを見る。'},
    {word:'聞く（きく）',meaning:'听/问',example:'音楽を聞く。'},
    {word:'話す（はなす）',meaning:'说',example:'日本語を話す。'},
    {word:'読む（よむ）',meaning:'读',example:'本を読む。'},
    {word:'書く（かく）',meaning:'写',example:'手紙を書く。'},
    {word:'買う（かう）',meaning:'买',example:'本を買う。'},
    {word:'する',meaning:'做',example:'宿題をする。'}],
  'ja-adj':[
    {word:'大きい（おおきい）',meaning:'大的',example:'大きい犬。'},
    {word:'小さい（ちいさい）',meaning:'小的',example:'小さい猫。'},
    {word:'新しい（あたらしい）',meaning:'新的',example:'新しい車。'},
    {word:'古い（ふるい）',meaning:'旧的',example:'古い本。'},
    {word:'高い（たかい）',meaning:'高/贵',example:'値段が高い。'},
    {word:'安い（やすい）',meaning:'便宜',example:'これは安い。'},
    {word:'美味しい（おいしい）',meaning:'好吃',example:'美味しい料理。'},
    {word:'綺麗（きれい）',meaning:'漂亮/干净',example:'綺麗な花。'},
    {word:'静か（しずか）',meaning:'安静',example:'静かな図書館。'},
    {word:'元気（げんき）',meaning:'健康',example:'元気な人。'}],
  'ja-adv':[
    {word:'～ている',meaning:'正在进行',example:'今、本を読んでいます。'},
    {word:'～てもいい',meaning:'可以…',example:'ここで食べてもいいですか。'},
    {word:'～なければならない',meaning:'必须',example:'早く帰らなければなりません。'},
    {word:'～たい',meaning:'想做',example:'日本へ行きたい。'},
    {word:'～たことがある',meaning:'曾经…过',example:'寿司を食べたことがある。'},
    {word:'～すぎる',meaning:'过度',example:'食べすぎました。'},
    {word:'可能形',meaning:'能/可以',example:'日本語が話せます。'},
    {word:'受身形',meaning:'被动',example:'先生に叱られました。'},
    {word:'使役形',meaning:'使役',example:'子供に掃除させました。'},
    {word:'～ながら',meaning:'一边…一边',example:'音楽を聞きながら勉強する。'},
    {word:'～ほうがいい',meaning:'最好',example:'医者に見せたほうがいい。'},
    {word:'～くらい',meaning:'大约/程度',example:'1時間くらい待った。'},
    {word:'～でしょう',meaning:'…吧',example:'明日は雨でしょう。'},
    {word:'～つもり',meaning:'打算',example:'来月旅行するつもりです。'}],
  'ja-short':[
    {word:'新聞（しんぶん）',meaning:'报纸',example:'新聞を読む。'},
    {word:'雑誌（ざっし）',meaning:'杂志',example:'雑誌を買う。'},
    {word:'天気（てんき）',meaning:'天气',example:'天気がいい。'},
    {word:'予定（よてい）',meaning:'预定',example:'今日の予定は？'},
    {word:'約束（やくそく）',meaning:'约定',example:'約束を守る。'},
    {word:'経験（けいけん）',meaning:'经验',example:'貴重な経験。'},
    {word:'将来（しょうらい）',meaning:'将来',example:'将来の夢。'},
    {word:'環境（かんきょう）',meaning:'环境',example:'環境にやさしい。'},
    {word:'社会（しゃかい）',meaning:'社会',example:'社会問題。'},
    {word:'経済（けいざい）',meaning:'经济',example:'経済成長。'},
    {word:'政治（せいじ）',meaning:'政治',example:'政治の話題。'},
    {word:'文化（ぶんか）',meaning:'文化',example:'日本文化。'}],
  'ja-honor':[
    {word:'お～になる',meaning:'尊敬（对方动作）',example:'先生はお帰りになりました。'},
    {word:'お～する',meaning:'自谦（自己动作）',example:'お送りします。'},
    {word:'いらっしゃる',meaning:'行く/来る/いる 的尊敬',example:'先生は教室にいらっしゃいます。'},
    {word:'おっしゃる',meaning:'言う 的尊敬',example:'先生がおっしゃいました。'},
    {word:'くださる',meaning:'くれる 的尊敬',example:'本をくださいました。'},
    {word:'ござる',meaning:'ある 的尊敬',example:'こちらにございます。'},
    {word:'さしあげる',meaning:'あげる 的自谦',example:'プレゼントをさしあげます。'},
    {word:'いただく',meaning:'もらう 的自谦',example:'ご意見をいただきました。'},
    {word:'申し上げる',meaning:'言う 的自谦',example:'よろしくお願い申し上げます。'},
    {word:'でございます',meaning:'です 的郑重',example:'8時でございます。'},
    {word:'お目にかかる',meaning:'会う 的自谦',example:'お目にかかれて光栄です。'},
    {word:'ご挨拶',meaning:'问候',example:'ご挨拶申し上げます。'},
    {word:'丁寧語',meaning:'礼貌语',example:'です・ます 体。'},
    {word:'尊敬語',meaning:'尊敬语',example:'目上の人に使う。'},
    {word:'謙譲語',meaning:'自谦语',example:'自分を下げる。'}],
  'ja-news':[
    {word:'経済成長',meaning:'经济增长',example:'経済成長が続いている。'},
    {word:'環境問題',meaning:'环境问题',example:'環境問題に取り組む。'},
    {word:'国際会議',meaning:'国际会议',example:'国際会議が開かれる。'},
    {word:'調査結果',meaning:'调查结果',example:'調査結果が発表された。'},
    {word:'技術革新',meaning:'技术革新',example:'技術革新が進む。'},
    {word:'医療現場',meaning:'医疗现场',example:'医療現場を支える。'},
    {word:'教育改革',meaning:'教育改革',example:'教育改革が始まる。'},
    {word:'文化遺産',meaning:'文化遗产',example:'世界文化遺産。'},
    {word:'政策決定',meaning:'政策决定',example:'政策を決定する。'},
    {word:'社会貢献',meaning:'社会贡献',example:'社会貢献活動。'},
    {word:'平和',meaning:'和平',example:'平和を願う。'},
    {word:'発展',meaning:'发展',example:'発展を続ける。'},
    {word:'挑戦',meaning:'挑战',example:'新たな挑戦。'},
    {word:'成果',meaning:'成果',example:'成果を上げる。'}],
  'ko-hangul':[
    {word:'ㄱ ㄴ ㄷ ㄹ ㅁ',meaning:'g/k n d/t r/l m',example:'가나다라마'},
    {word:'ㅂ ㅅ ㅇ ㅈ ㅊ',meaning:'p/b s ng j ch',example:'바사아자차'},
    {word:'ㅋ ㅌ ㅍ ㅎ',meaning:'k t p h',example:'카타파하'},
    {word:'ㅏ ㅑ ㅓ ㅕ ㅗ',meaning:'a ya eo yeo o',example:'가갸겨교고'},
    {word:'ㅛ ㅜ ㅠ ㅡ ㅣ',meaning:'yo u yu eu i',example:'교규그기'},
    {word:'안녕',meaning:'你好/再见',example:'안녕, 친구야.'},
    {word:'안녕하세요',meaning:'您好',example:'안녕하세요, 선생님.'},
    {word:'감사합니다',meaning:'谢谢',example:'정말 감사합니다.'},
    {word:'미안합니다',meaning:'对不起',example:'늦어서 미안합니다.'},
    {word:'주세요',meaning:'请给我',example:'커피 주세요.'},
    {word:'어서 오세요',meaning:'欢迎',example:'어서 오세요, 반갑습니다.'},
    {word:'잘 지내세요?',meaning:'你过得好吗？',example:'요즘 잘 지내세요?'},
    {word:'또 봐요',meaning:'再见',example:'내일 또 봐요.'},
    {word:'좋아요',meaning:'好/喜欢',example:'이 옷은 정말 좋아요.'}],
  'ko-intro':[
    {word:'이름',meaning:'名字',example:'제 이름은 김민수입니다.'},
    {word:'나이',meaning:'年龄',example:'스무 살입니다.'},
    {word:'직업',meaning:'职业',example:'직업은 학생입니다.'},
    {word:'국적',meaning:'国籍',example:'중국에서 왔습니다.'},
    {word:'취미',meaning:'爱好',example:'취미는 음악 감상입니다.'},
    {word:'가족',meaning:'家人',example:'가족은 네 명입니다.'},
    {word:'사는 곳',meaning:'住处',example:'서울에 삽니다.'},
    {word:'전화번호',meaning:'电话号码',example:'전화번호 좀 알려주세요.'},
    {word:'생일',meaning:'生日',example:'생일은 3월 15일입니다.'},
    {word:'언어',meaning:'语言',example:'한국어를 조금 할 수 있어요.'}],
  'ko-num':[
    {word:'하나 둘 셋',meaning:'1 2 3（固有数）',example:'사과 하나 주세요.'},
    {word:'넷 다섯 여섯',meaning:'4 5 6',example:'여섯 시입니다.'},
    {word:'일 이 삼',meaning:'1 2 3（汉字数）',example:'이층입니다.'},
    {word:'사 오 육',meaning:'4 5 6',example:'오 분 기다렸어요.'},
    {word:'칠 팔 구',meaning:'7 8 9',example:'팔 시.'},
    {word:'십',meaning:'10',example:'십 시.'},
    {word:'시간',meaning:'时间/小时',example:'한 시간.'},
    {word:'분',meaning:'分钟',example:'오분만 더 주세요.'},
    {word:'날짜',meaning:'日期',example:'오늘 날짜가 뭐예요?'}],
  'ko-food':[
    {word:'김치',meaning:'泡菜',example:'김치를 좋아해요.'},
    {word:'비빔밥',meaning:'拌饭',example:'비빔밥 한 그릇 주세요.'},
    {word:'불고기',meaning:'烤肉',example:'불고기는 맛있어요.'},
    {word:'라면',meaning:'拉面',example:'라면을 끓여요.'},
    {word:'떡볶이',meaning:'炒年糕',example:'떡볶이를 좋아해요.'},
    {word:'삼겹살',meaning:'五花肉',example:'삼겹살 구워 먹어요.'},
    {word:'김밥',meaning:'紫菜包饭',example:'김밥을 만들어요.'},
    {word:'국',meaning:'汤',example:'된장국을 끓여요.'},
    {word:'커피',meaning:'咖啡',example:'아이스 커피 주세요.'},
    {word:'차',meaning:'茶',example:'녹차 한 잔.'},
    {word:'물',meaning:'水',example:'물 좀 주세요.'},
    {word:'빵',meaning:'面包',example:'식빵을 샀어요.'}],
  'ko-verb':[
    {word:'가다',meaning:'去',example:'학교에 가요.'},
    {word:'오다',meaning:'来',example:'집에 왔어요.'},
    {word:'먹다',meaning:'吃',example:'밥을 먹어요.'},
    {word:'마시다',meaning:'喝',example:'물을 마셔요.'},
    {word:'보다',meaning:'看',example:'영화를 봐요.'},
    {word:'듣다',meaning:'听',example:'음악을 들어요.'},
    {word:'읽다',meaning:'读',example:'책을 읽어요.'},
    {word:'쓰다',meaning:'写',example:'편지를 써요.'},
    {word:'사다',meaning:'买',example:'과일을 샀어요.'},
    {word:'하다',meaning:'做',example:'공부를 해요.'},
    {word:'좋아하다',meaning:'喜欢',example:'한식을 좋아해요.'}],
  'ko-tense':[
    {word:'～았/었어요',meaning:'过去式',example:'어제 친구를 만났어요.'},
    {word:'～(으)ㄹ 거예요',meaning:'将来时',example:'내일 학교에 갈 거예요.'},
    {word:'～고 있어요',meaning:'正在进行',example:'지금 책을 읽고 있어요.'},
    {word:'～던',meaning:'过去持续',example:'예전에 자주 가던 식당.'},
    {word:'～아/어야 해요',meaning:'必须',example:'일찍 일어나야 해요.'},
    {word:'～고 싶어요',meaning:'想做',example:'한국에 가고 싶어요.'},
    {word:'～ㄹ/을 수 있어요',meaning:'能/可以',example:'한국어를 할 수 있어요.'},
    {word:'～지 말아요',meaning:'请不要',example:'여기서 사진 찍지 말아요.'},
    {word:'～아/어 봐요',meaning:'试着做',example:'한번 해 봐요.'},
    {word:'～는 중이에요',meaning:'在…中',example:'준비하는 중이에요.'},
    {word:'～았/었어야 했어요',meaning:'本该做（没做）',example:'일찍 왔어야 했어요.'},
    {word:'～지 않았어요',meaning:'没做',example:'어제 공부하지 않았어요.'},
    {word:'～ㄴ/은 적이 있어요',meaning:'曾经…过',example:'한국에 가 본 적이 있어요?'},
    {word:'～ㄹ/을까요?',meaning:'要不要…?',example:'뭐 먹을까요?'}],
  'ko-reading':[
    {word:'뉴스',meaning:'新闻',example:'아침 뉴스를 봤어요.'},
    {word:'기사',meaning:'报道/文章',example:'신문 기사를 읽어요.'},
    {word:'소설',meaning:'小说',example:'한국 소설을 읽어요.'},
    {word:'시',meaning:'诗',example:'시를 좋아해요.'},
    {word:'잡지',meaning:'杂志',example:'패션 잡지.'},
    {word:'만화',meaning:'漫画',example:'만화를 좋아해요.'},
    {word:'광고',meaning:'广告',example:'TV 광고.'},
    {word:'편지',meaning:'信',example:'친구에게 편지를 써요.'},
    {word:'일기',meaning:'日记',example:'매일 일기를 써요.'},
    {word:'보고서',meaning:'报告',example:'업무 보고서.'},
    {word:'논문',meaning:'论文',example:'석사 논문.'},
    {word:'수필',meaning:'随笔',example:'수필을 써요.'}],
  'ko-caus':[
    {word:'～시키다',meaning:'使役（让做）',example:'학생들에게 숙제를 시켜요.'},
    {word:'～게 하다',meaning:'使（让某人做）',example:'친구를 기다리게 했어요.'},
    {word:'～도록 하다',meaning:'使…（强调）',example:'모두 이해하도록 설명해요.'},
    {word:'～아/어지다',meaning:'被动/变得',example:'창문이 열려 있어요.'},
    {word:'～ㄹ/을 수밖에 없어요',meaning:'只好…',example:'그냥 갈 수밖에 없어요.'},
    {word:'～아/어 보이다',meaning:'看起来',example:'맛있어 보여요.'},
    {word:'～는 대로',meaning:'一…就',example:'도착하는 대로 전화할게요.'},
    {word:'～다 보면',meaning:'做着做着就',example:'매일 하다 보면 익숙해져요.'},
    {word:'～ㄴ/은 채로',meaning:'保持…状态',example:'옷을 입은 채로 잤어요.'},
    {word:'～더니',meaning:'做了之后（发现）',example:'열어 보니 아무도 없었어요.'},
    {word:'～ㄹ/을 뿐만 아니라',meaning:'不仅…而且',example:'맛있을 뿐만 아니라 건강에도 좋아요.'},
    {word:'～는 반면에',meaning:'另一方面',example:'가격은 싼 반면에 품질은 좋아요.'},
    {word:'～던 참이에요',meaning:'刚刚在做…',example:'방금 전화하던 참이에요.'},
    {word:'～ㄹ/을 따름이에요',meaning:'只不过…',example:'그저 노력할 따름이에요.'},
    {word:'～아/어도 그만이에요',meaning:'大不了…',example:'늦어도 그만이에요.'}],
  'ko-essay':[
    {word:'주제',meaning:'主题',example:'주제를 정해요.'},
    {word:'논지',meaning:'论点',example:'논지를 세워요.'},
    {word:'근거',meaning:'根据',example:'근거를 들어요.'},
    {word:'결론',meaning:'结论',example:'결론을 내려요.'},
    {word:'비판',meaning:'批评',example:'비판적인 시각.'},
    {word:'찬성',meaning:'赞成',example:'찬성하는 입장.'},
    {word:'반대',meaning:'反对',example:'반대 의견.'},
    {word:'입장',meaning:'立场',example:'나의 입장은.'},
    {word:'배경',meaning:'背景',example:'역사적 배경.'},
    {word:'현상',meaning:'现象',example:'사회적 현상.'},
    {word:'원인',meaning:'原因',example:'원인을 분석해요.'},
    {word:'해결',meaning:'解决',example:'문제를 해결해요.'},
    {word:'영향',meaning:'影响',example:'큰 영향을 줘요.'},
    {word:'발전',meaning:'发展',example:'지속적인 발전.'}]
};

/* 语法练习 —— 选择题 */
const GRAMMAR = {
  en:[
    {level:'A1', q:'She ___ a student.', a:['is','are','am','be'], c:0, e:'第三人称单数用 is。'},
    {level:'A1', q:'I ___ from China.', a:['am','is','are','be'], c:0, e:'I 用 am。'},
    {level:'A1', q:'They ___ friends.', a:['is','am','are','be'], c:2, e:'复数用 are。'},
    {level:'A2', q:'He ___ to school every day.', a:['go','goes','going','went'], c:1, e:'第三人称单数现在时加 es。'},
    {level:'A2', q:'I ___ breakfast at 7 yesterday.', a:['have','has','had','having'], c:2, e:'过去时用 had。'},
    {level:'B1', q:'If I ___ rich, I would travel.', a:['am','was','were','be'], c:2, e:'虚拟语气与现在事实相反用 were。'},
    {level:'B1', q:'She asked me where I ___.', a:['live','lives','lived','living'], c:2, e:'宾语从句时态一致。'},
    {level:'B2', q:'The book ___ by millions.', a:['read','reads','is read','reading'], c:2, e:'被动语态。'},
    {level:'B2', q:'Not until midnight ___ home.', a:['he went','did he go','he did go','went he'], c:1, e:'Not until 引导的倒装句。'}],
  ja:[
    {level:'N5', q:'わたし ___ 学生です。', a:['は','が','を','に'], c:0, e:'主题提示用は。'},
    {level:'N5', q:'りんご ___ 食べます。', a:['は','が','を','に'], c:2, e:'他动词宾语用を。'},
    {level:'N4', q:'昨日、映画を ___ 。', a:['見る','見ます','見ました','見て'], c:2, e:'昨日发生的动作用过去式。'},
    {level:'N4', q:'明日、デパート ___ 行きます。', a:['に','で','を','へ'], c:0, e:'目的地用に或へ。'},
    {level:'N3', q:'子供の時、よく公園で ___ 。', a:['遊ぶ','遊んだ','遊びます','遊んでいる'], c:1, e:'过去的习惯用过去式。'},
    {level:'N3', q:'彼は日本に3年 ___ 住んでいます。', a:['を','に','で','から'], c:1, e:'期间+ に（に居住地点用に。'},
    {level:'N2', q:'先生、ご意見を ___ 。', a:['聞きました','お聞きしました','聞かせました','聞かれました'], c:1, e:'对老师用自谦语お聞きしました。'},
    {level:'N2', q:'社長が会議室に ___ 。', a:['いらっしゃいます','います','おります','あります'], c:0, e:'对社长用尊敬语いらっしゃいます。'}],
  ko:[
    {level:'1', q:'저 ___ 학생입니다.', a:['는','은','이','가'], c:1, e:'저后面用은。'},
    {level:'1', q:'사과 ___ 먹어요.', a:['를','을','이','가'], c:1, e:'사과（有收音）+을。'},
    {level:'2', q:'어제 친구를 ___ .', a:['만나요','만났어요','만날 거예요','만나고 있어요'], c:1, e:'어제（昨天）用过去式。'},
    {level:'2', q:'학교 ___ 가요.', a:['에','에서','으로','까지'], c:0, e:'目的地用에。'},
    {level:'3', q:'한국에 가 ___ .', a:['고 싶어요','고 있어요','지 않아요','아/어요'], c:0, e:'想去韩国。'},
    {level:'3', q:'지금 책을 읽 ___ .', a:['고 싶어요','고 있어요','지 말아요','았어요'], c:1, e:'正在读书。'},
    {level:'4', q:'그는 부자 ___ 여행을 많이 했어요.', a:['는 대로','뿐만 아니라','면서','는 반면에'], c:1, e:'不仅有钱而且旅行多。'},
    {level:'4', q:'나는 노력 ___ .', a:['할 따름이에요','하는 대로','하다 보면','는 참이에요'], c:0, e:'我只不过努力罢了。'}]
};

/* 口语跟读 */
const SPEAKING = {
  en:[
    {s:'Hello, how are you today?', t:'你好，你今天怎么样？', d:'日常问候'},
    {s:'I would like a cup of coffee, please.', t:'请给我一杯咖啡。', d:'点餐'},
    {s:'Thank you very much for your help.', t:'非常感谢你的帮助。', d:'感谢'},
    {s:'Excuse me, where is the train station?', t:'打扰一下，请问火车站在哪里？', d:'问路'},
    {s:'Nice to meet you. My name is Sarah.', t:'很高兴认识你。我叫Sarah。', d:'自我介绍'},
    {s:'Could you repeat that, please?', t:'你能再说一遍吗？', d:'请求重复'},
    {s:'I am learning English because I want to travel.', t:'我在学英语因为我想去旅行。', d:'表达原因'},
    {s:'What do you do for work?', t:'你做什么工作？', d:'询问职业'},
    {s:'Let us meet tomorrow afternoon.', t:'我们明天下午见面吧。', d:'约定'},
    {s:'The weather is really nice today.', t:'今天天气真好。', d:'闲聊天气'}],
  ja:[
    {s:'こんにちは、田中です。', t:'你好，我是田中。', d:'自我介绍'},
    {s:'おはようございます。', t:'早上好。', d:'问候'},
    {s:'ありがとうございます。', t:'非常感谢。', d:'感谢'},
    {s:'すみません、駅はどこですか。', t:'请问，车站在哪里？', d:'问路'},
    {s:'よろしくお願いします。', t:'请多关照。', d:'寒暄'},
    {s:'今日はいい天気ですね。', t:'今天天气真好。', d:'闲聊'},
    {s:'もう一度お願いします。', t:'请再说一遍。', d:'请求重复'},
    {s:'日本語を勉強しています。', t:'我正在学习日语。', d:'自我说明'}],
  ko:[
    {s:'안녕하세요, 저는 김민수예요.', t:'你好，我是金敏秀。', d:'自我介绍'},
    {s:'만나서 반갑습니다.', t:'很高兴见到你。', d:'问候'},
    {s:'감사합니다.', t:'谢谢。', d:'感谢'},
    {s:'실례합니다, 지하철역이 어디예요?', t:'请问，地铁站在哪里？', d:'问路'},
    {s:'잘 부탁드립니다.', t:'请多关照。', d:'寒暄'},
    {s:'오늘 날씨가 정말 좋네요.', t:'今天天气真好。', d:'闲聊'},
    {s:'한국어를 조금 할 수 있어요.', t:'我会一点韩语。', d:'自我说明'},
    {s:'커피 한 잔 주세요.', t:'请给我一杯咖啡。', d:'点餐'}]
};

/* 听力练习 */
const LISTENING = {
  en:[
    {d:'Man: Excuse me, how much is this book? Woman: It is 25 dollars.', q:'How much is the book?', a:['$15','$25','$35','$45'], c:1},
    {d:'Woman: What time does the movie start? Man: It starts at 7:30 pm.', q:'When does the movie start?', a:['6:30 pm','7:00 pm','7:30 pm','8:00 pm'], c:2},
    {d:'Man: I would like to order a coffee and a sandwich, please. Woman: Sure, anything else?', q:'What does the man want?', a:['Tea and cake','Coffee and sandwich','Water and bread','Juice and salad'], c:1},
    {d:'Woman: Where are you from? Man: I am from Tokyo, Japan.', q:'Where is the man from?', a:['Beijing','Seoul','Tokyo','New York'], c:2},
    {d:'Man: How do you go to work every day? Woman: I usually take the subway.', q:'How does the woman go to work?', a:['By car','By bus','By subway','By bike'], c:2},
    {d:'Woman: What is your favorite season? Man: I love summer because I love swimming.', q:'Why does the man like summer?', a:['He likes hiking','He loves swimming','He enjoys reading','He likes skiing'], c:1},
    {d:'Man: Sorry I am late. The bus was delayed. Woman: No problem, the meeting has not started yet.', q:'Why was the man late?', a:['He overslept','The bus was delayed','He forgot the time','His car broke down'], c:1},
    {d:'Woman: Could you recommend a good restaurant nearby? Man: Sure, there is an excellent Italian place around the corner.', q:'What kind of restaurant does the man recommend?', a:['Chinese','Japanese','Italian','Mexican'], c:2},
    {d:'Man: I need to return this book to the library. Woman: It is due tomorrow.', q:'When is the book due?', a:['Today','Tomorrow','Next week','Yesterday'], c:1},
    {d:'Woman: How long have you been studying English? Man: For about three years now.', q:'How long has the man studied English?', a:['One year','Two years','Three years','Four years'], c:2}],
  ja:[
    {d:'男：すみません、この本はいくらですか。 女：2,500円です。', q:'本はいくらですか。', a:['1,500円','2,500円','3,500円','4,500円'], c:1},
    {d:'女：映画は何時に始まりますか。 男：7時半です。', q:'映画は何時に始まりますか。', a:['6時','7時','7時半','8時'], c:2},
    {d:'男：コーヒーとサンドイッチをお願いします。 女：かしこまりました。', q:'男の人は何を注文しましたか。', a:['紅茶とケーキ','コーヒーとサンドイッチ','水とパン','ジュースとサラダ'], c:1},
    {d:'女：どちらからいらっしゃいましたか。 男：東京から来ました。', q:'男の人はどこから来ましたか。', a:['大阪','東京','京都','横浜'], c:1},
    {d:'男：毎日どうやって会社へ行きますか。 女：いつも地下鉄です。', q:'女の人はどうやって会社へ行きますか。', a:['車','バス','地下鉄','自転車'], c:2},
    {d:'女：好きな季節は何ですか。 男：夏が大好きです。水泳が好きだから。', q:'男の人はどうして夏が好きですか。', a:['山登りが好き','水泳が好き','読書が好き','スキーが好き'], c:1},
    {d:'男：遅れてすみません。バスが遅れました。 女：大丈夫ですよ、まだ会議は始まっていません。', q:'男の人はどうして遅れましたか。', a:['寝坊した','バスが遅れた','時間を忘れた','車が故障した'], c:1},
    {d:'女：近くにいいレストランを知りませんか。 男：角を曲がったところにイタリア料理のお店がありますよ。', q:'男の人はどんなレストランを勧めましたか。', a:['中華','日本','イタリア','メキシコ'], c:2}],
  ko:[
    {d:'남: 실례합니다, 이 책은 얼마예요?  여: 25,000원이에요.', q:'책은 얼마입니까?', a:['15,000원','25,000원','35,000원','45,000원'], c:1},
    {d:'여: 영화는 몇 시에 시작해요?  남: 7시 반이에요.', q:'영화는 언제 시작합니까?', a:['6시','7시','7시 반','8시'], c:2},
    {d:'남: 커피와 샌드위치 주세요.  여: 네, 알겠습니다.', q:'남자는 무엇을 주문했습니까?', a:['차와 케이크','커피와 샌드위치','물과 빵','주스와 샐러드'], c:1},
    {d:'여: 어디에서 오셨어요?  남: 서울에서 왔어요.', q:'남자는 어디에서 왔습니까?', a:['부산','서울','인천','대구'], c:1},
    {d:'남: 매일 어떻게 학교에 가요?  여: 보통 지하철로 가요.', q:'여자는 어떻게 학교에 갑니까?', a:['차로','버스로','지하철로','자전거로'], c:2},
    {d:'여: 제일 좋아하는 계절이 뭐예요?  남: 여름을 좋아해요. 수영을 좋아하기 때문이에요.', q:'남자는 왜 여름을 좋아합니까?', a:['등산을 좋아해서','수영을 좋아해서','독서를 좋아해서','스키를 좋아해서'], c:1},
    {d:'남: 늦어서 미안합니다. 버스가 늦었어요.  여: 괜찮아요, 아직 시작 안 했어요.', q:'남자는 왜 늦었습니까?', a:['잠을 자다','버스가 늦다','시간을 잊다','차가 고장 나다'], c:1},
    {d:'여: 가까운 맛있는 음식점 좀 추천해 줄래요?  남: 네, 모퉁이에 맛있는 이탈리아 식당이 있어요.', q:'남자는 어떤 음식점을 추천했습니까?', a:['중식','한식','이탈리아','멕시코'], c:2}]
};

/* 成就徽章 */
const ACHIEVEMENTS = [
  { id:'first_login', icon:'🎉', name:'初次登录', desc:'完成首次登录 LinguaVerse', need: user => user.createdAt },
  { id:'word_10',    icon:'📖', name:'词汇入门', desc:'学习 10 个单词', need: user => user.stats && user.stats.words >= 10 },
  { id:'word_50',    icon:'📚', name:'词汇达人', desc:'学习 50 个单词', need: user => user.stats && user.stats.words >= 50 },
  { id:'word_100',   icon:'🏆', name:'词汇大师', desc:'学习 100 个单词', need: user => user.stats && user.stats.words >= 100 },
  { id:'grammar_5',  icon:'✍️', name:'语法入门', desc:'完成 5 道语法题', need: user => user.stats && user.stats.grammar >= 5 },
  { id:'speak_5',    icon:'🎤', name:'开口说话', desc:'完成 5 次口语跟读', need: user => user.stats && user.stats.speaking >= 5 },
  { id:'listen_5',   icon:'🎧', name:'听音辨意', desc:'完成 5 次听力训练', need: user => user.stats && user.stats.listening >= 5 },
  { id:'streak_3',   icon:'🔥', name:'连续 3 天', desc:'连续学习 3 天', need: user => user.streak && user.streak >= 3 },
  { id:'streak_7',   icon:'⭐', name:'坚持一周', desc:'连续学习 7 天', need: user => user.streak && user.streak >= 7 },
  { id:'unit_1',     icon:'✅', name:'完成单元', desc:'完成任意一个学习单元', need: user => user.completedUnits && user.completedUnits.length >= 1 },
  { id:'multi_lang', icon:'🌍', name:'多语学习者', desc:'学习 2 种及以上语言', need: user => user.learnedLangs && user.learnedLangs.length >= 2 },
  { id:'community',  icon:'💬', name:'社区贡献', desc:'在社区发布 1 条帖子', need: user => user.stats && user.stats.posts >= 1 }
];

/* 种子社区帖子 */
const SEED_POSTS = [
  { id:'p1', author:'小琳', lang:'en', tag:'学习心得', time:'2 小时前', content:'刚完成英语 A2 单元，每天坚持 20 分钟真的有效！分享给大家，坚持就是胜利 🌟', likes:12, replies:3 },
  { id:'p2', author:'Hiro', lang:'ja', tag:'经验分享', time:'昨天', content:'日语 N5 五十音建议先练习あ行再扩展到か行，每天 10 个假名比较轻松。', likes:18, replies:5 },
  { id:'p3', author:'韩语小白', lang:'ko', tag:'求助', time:'3 天前', content:'한글 的收音总是记不住，求大佬分享记忆技巧？', likes:7, replies:8 },
  { id:'p4', author:'Alex', lang:'en', tag:'资源推荐', time:'5 天前', content:'推荐大家每天听 5 分钟英语播客「6-minute English」，对听力提升特别有帮助！', likes:25, replies:6 },
  { id:'p5', author:'日语爱好者', lang:'ja', tag:'学习心得', time:'一周前', content:'敬语是日语最大难点之一，建议先记住尊敬语和自谦语的动词变化，再慢慢积累。', likes:30, replies:11 }
];
